// SPDX-License-Identifier: MIT
pragma solidity 0.8.17;

library HeadData {
    function traits(uint256 i) external pure returns (string memory) {
        if (i == 0) return "Beanie Orange";
        if (i == 1) return "Beanie Black";
        if (i == 2) return "Beanie Red";
        if (i == 3) return "Beanie Purple";
        if (i == 4) return "Punk Blue";
        if (i == 5) return "Punk Blonde";
        if (i == 6) return "Punk Green";
        if (i == 7) return "Bandana Red";
        if (i == 8) return "Bandana Blue";
        if (i == 9) return "Bandana Purple";
        if (i == 10) return "Straw Hat";
        if (i == 11) return "Top Hat";
        if (i == 12) return "Gold Crown";
        if (i == 13) return "Backwards Cap Green";
        if (i == 14) return "Backwards Cap Orange";
        if (i == 15) return "Backwards Cap Pink";
        if (i == 16) return "Backwards Cap Blue";
        if (i == 17) return "Pot";
        if (i == 18) return "Aluminum Hat";
        if (i == 19) return "Party Hat";
        if (i == 20) return "Propeller Hat";
        if (i == 21) return "Cowboy Hat";
        if (i == 22) return "Red Hat";
        if (i == 23) return "Black Hat";
        if (i == 24) return "White Hat";
        if (i == 25) return "Wizard Hat";
        if (i == 26) return "Hard Hat";
        if (i == 27) return "Single Strand";
        if (i == 28) return "Cropped Brunette";
        if (i == 29) return "Cropped Ginger";
        if (i == 30) return "Cropped Blonde";
        if (i == 31) return "Cropped Gray";
        if (i == 32) return "Cropped Black";
        if (i == 33) return "Bob Brunette";
        if (i == 34) return "Bob Ginger";
        if (i == 35) return "Bob Blonde";
        if (i == 36) return "Bob Gray";
        if (i == 37) return "Bob Black";
        if (i == 38) return "Santa Hat";
        if (i == 39) return "Knight Helmet";
        if (i == 40) return "Royale Knight Helmet";
        if (i == 41) return "Black Knight Helmet";
        if (i == 42) return "Ninja Headband";
        if (i == 43) return "Wagie";
        if (i == 44) return "Cap Blue";
        if (i == 45) return "Cap Pink";
        if (i == 46) return "Cap Orange";
        if (i == 47) return "Cap Green";
        if (i == 48) return "Diving Gear";
        if (i == 49) return "Chefs Hat";
        if (i == 50) return "Sapling";
        if (i == 51) return "Flower Crown";
        if (i == 52) return "Green Feelers";
        if (i == 53) return "Clown";
        if (i == 54) return "Antenna";
        if (i == 55) return "Rice Hat";
        if (i == 56) return "Halo";
        if (i == 57) return "Pilot Helmet";
        if (i == 58) return "Headphones Red";
        if (i == 59) return "Headphones Green";
        if (i == 60) return "Headphones Blue";
        if (i == 61) return "Pompadour Brunette";
        if (i == 62) return "Pompadour Ginger";
        if (i == 63) return "Pompadour Blonde";
        if (i == 64) return "Pompadour Gray";
        if (i == 65) return "Pompadour Black";
        if (i == 66) return "Perm Brunette";
        if (i == 67) return "Perm Ginger";
        if (i == 68) return "Perm Blonde";
        if (i == 69) return "Perm Gray";
        if (i == 70) return "Perm Black";
        if (i == 71) return "Half Bald Brunette";
        if (i == 72) return "Half Bald Ginger";
        if (i == 73) return "Half Bald Blonde";
        if (i == 74) return "Half Bald Gray";
        if (i == 75) return "Half Bald Black";
        if (i == 76) return "Ponytail Pink";
        if (i == 77) return "Ponytail Brunette";
        if (i == 78) return "Ponytail Ginger";
        if (i == 79) return "Ponytail Blonde";
        if (i == 80) return "Ponytail Gray";
        if (i == 81) return "Ponytail Black";
        if (i == 82) return "Grunge Green";
        if (i == 83) return "Grunge Brunette";
        if (i == 84) return "Grunge Ginger";
        if (i == 85) return "Grunge Blonde";
        if (i == 86) return "Grunge Gray";
        if (i == 87) return "Grunge Black";
        if (i == 88) return "Sombrero";
        if (i == 89) return "Fez hat";
        if (i == 90) return "Captain Hat";
        if (i == 91) return "Buzzcut Brunette";
        if (i == 92) return "Buzzcut Ginger";
        if (i == 93) return "Buzzcut Blonde";
        if (i == 94) return "Buzzcut Gray";
        if (i == 95) return "Buzzcut Black";
        if (i == 96) return "Balaclava Black";
        if (i == 97) return "Balaclava Orange";
        if (i == 98) return "Balaclava Pink";
        if (i == 99) return "None";

        revert("head idx");
    }
}
